services:
  accounts_context_db:
    image: postgres:alpine
    container_name: accounts_context_db
    env_file:
      - .db.env
    ports:
      - 15432:5432
    volumes:
      - ./mount/:/var/lib/postgresql/data
    restart: on-failure
    networks:
      - overkilled_network

  accounts_context_api:
    build:
      context: ../../
      dockerfile: bounded_contexts/accounts_context/accounts_context/api_svc/Dockerfile
    command:
      sh -c "cd /app/bounded_contexts/accounts_context/accounts_context/api_svc &&\
      /etc/poetry/bin/poetry run uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    container_name: accounts_context_api
    volumes:
      - ./accounts_context/api_svc:/app/bounded_contexts/accounts_context/accounts_context/api_svc
      - ./accounts_context/alembic:/app/bounded_contexts/accounts_context/accounts_context/alembic
      - ./accounts_context/db:/app/bounded_contexts/accounts_context/accounts_context/db
      - ./accounts_context/utils:/app/bounded_contexts/accounts_context/accounts_context/utils
      - ./accounts_context/config.py:/app/bounded_contexts/accounts_context/accounts_context/config.py
      - ../../libs/common_lib:/app/libs/common_lib
      - ../../libs/events_framework:/app/libs/events_framework
    env_file:
      - .env
    ports:
      - 18000:8000
    restart: on-failure
    depends_on:
      - accounts_context_db
    networks:
      - overkilled_network

networks:
  overkilled_network:
    external: true
