from os import environ as env

BOUNDED_CONTEXT_NAME = "todos_context"

DB_HOST = env.get("DB_HOST", f"{BOUNDED_CONTEXT_NAME}_db")
DB_PORT = env.get("DB_PORT", "5432")
DB_USER = env.get("DB_USER")
DB_PASSWORD = env.get("DB_PASSWORD")
DB_NAME = env.get("DB_NAME")

RABBITMQ_HOST = env["RABBITMQ_HOST"]
RABBITMQ_PORT = env.get("RABBITMQ_PORT", "5672")
RABBITMQ_USERNAME = env["RABBITMQ_USERNAME"]
RABBITMQ_PASSWORD = env["RABBITMQ_PASSWORD"]
RABBITMQ_VIRTUAL_HOST = env.get("RABBITMQ_VIRTUAL_HOST", "/")
RABBITMQ_USERS_QUEUE_NAME = env["RABBITMQ_USERS_QUEUE_NAME"]
