"""moved user to todo category

Revision ID: 272bd3da3a99
Revises: c9255bc2aabd
Create Date: 2024-12-20 06:50:35.227382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '272bd3da3a99'
down_revision: Union[str, None] = 'c9255bc2aabd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo_categories', sa.Column('user', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'todo_categories', 'users', ['user'], ['id'])
    op.drop_constraint('todos_user_fkey', 'todos', type_='foreignkey')
    op.drop_column('todos', 'user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('user', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('todos_user_fkey', 'todos', 'users', ['user'], ['id'])
    op.drop_constraint(None, 'todo_categories', type_='foreignkey')
    op.drop_column('todo_categories', 'user')
    # ### end Alembic commands ###
